version: "2017-09-20"
pipeline:
  - id: build
    type: script
    commands:
      - desc: "Install dependencies"
        cmd: |
          apt-get update
          apt-get install -y --fix-missing \
          openjdk-8-* \
          maven \
          git
          curl -fLOsS https://delivery.cloud.zalando.com/utils/ensure-docker && sh ensure-docker && rm ensure-docker

      - desc: "Build maven package"
        cmd: |
          ./mvnw clean package

      - desc: "Push Docker Image"
        cmd: |
          IS_PR_BUILD=${CDP_PULL_REQUEST_NUMBER+"true"}
          if [[ ${IS_PR_BUILD} != "true" ]]
          then
            RELEASE_VERSION=$(git describe --tags --always --dirty)
            AGENT_IMAGE=registry-write.opensource.zalan.do/zmon/zmon-controller:${RELEASE_VERSION}
          else
            AGENT_IMAGE=registry-write.opensource.zalan.do/zmon/zmon-controller-unstable:${CDP_BUILD_VERSION}
          fi
          docker build --tag "$AGENT_IMAGE" .
          docker push "$AGENT_IMAGE"
          git gh-tag ${RELEASE_VERSION:-CDP_BUILD_VERSION}
